### PR TITLE
Fix redirect about old /weblog/ paths

### PR DESCRIPTION
**Pull request by jairlopez**
These links are broken:

- In [sconfig/README.markdown](https://github.com/arp242/sconfig/blob/3918df107cea135365af8c4e95e709038d01faa7/README.markdown): 
   - http://arp242.net/weblog/JSON_as_configuration_files-_please_dont.html
   - http://arp242.net/weblog/yaml_probably_not_so_great_after_all.html

- In [packman.vim/README.markdown](https://github.com/arp242/packman.vim/blob/8720b59ce470929a7aa2cf32c350a6c650eb6271/README.markdown):
   - https://arp242.net/weblog/i-dont-like-git-but-im-going-to-migrate-my-projects-to-it.html

They’re so because these rules are skipped after processing this one:
https://github.com/arp242/arp242.net/blob/b554710aeba4f6976d58e6b5a69dfe4955d7b849/_redirects#L8

That’s the proper behavior according to Netlify’s documentation [here](https://docs.netlify.com/routing/redirects/#rule-processing-order): 
> The redirects engine will process the first matching rule it finds, reading from top to bottom.

These links might be up again by merging these changes.

### CODE REVIEW

**Comment by arp242** [comment]
Oops! This is because I changed the order in 472db2c. I changed it back now.

Thanks for reporting!

**Comment by jairlopez** [comment]
You're welcome!

**Comment by jairlopez** [comment]
What about this redirect? Is it ok? The `/weblog` part appears twice.
https://github.com/arp242/arp242.net/blob/4970c060a11e96499fd742e899853a2669df9a86/_redirects#L32

**Comment by arp242** [comment]
Yeah, that's not correct. I'll fix later. Thanks again

**Pull request closed without merging**
